create table if not exists public.categories (
	id bigint generated by default as identity primary key,
	name text not null unique,
	sort_order integer not null default 0,
	created_at timestamptz not null default now()
);

create table if not exists public.products (
	id bigint generated by default as identity primary key,
	category_id bigint not null references public.categories(id) on delete restrict,
	name text not null,
	price integer not null check (price >= 0),
	badge text,
	badge_class text,
	image_url text not null,
	description text not null,
	light text not null check (light in ('Сонце', 'Напівтінь', 'Тінь')),
	container text not null default 'C3-C5',
	winter_hardiness text not null default 'Висока',
	in_stock boolean not null default true,
	is_active boolean not null default true,
	sort_order integer not null default 0,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
	user_id uuid primary key references auth.users(id) on delete cascade,
	created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
	select exists (
		select 1
		from public.admin_users
		where user_id = auth.uid()
	);
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create or replace view public.catalog_products
with (security_invoker = true) as
select
	p.id,
	p.name,
	c.name as category,
	p.category_id,
	p.price,
	p.badge,
	p.badge_class,
	p.image_url as image,
	p.description,
	p.light,
	p.container,
	p.winter_hardiness,
	p.in_stock,
	p.is_active,
	p.sort_order,
	p.created_at,
	p.updated_at
from public.products p
join public.categories c on c.id = p.category_id;

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.admin_users enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.catalog_products to anon, authenticated;
grant select on public.categories to anon, authenticated;
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;
grant insert, update, delete on public.products to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories"
on public.categories for select
using (true);

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
using (is_active = true);

drop policy if exists "Admins can manage categories" on public.categories;
create policy "Admins can manage categories"
on public.categories for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products"
on public.products for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can read admin users" on public.admin_users;
create policy "Admins can read admin users"
on public.admin_users for select
using (user_id = auth.uid() or public.is_admin());

insert into public.categories (name, sort_order) values
	('Декоративні кущі', 10),
	('Хвойні рослини', 20),
	('Садові рослини', 30),
	('Сезонні рослини', 40),
	('Плодові рослини', 50),
	('Багаторічні рослини', 60),
	('В’юнкі рослини', 70)
on conflict (name) do nothing;

insert into public.products (id, name, category_id, price, badge, badge_class, image_url, description, light, sort_order)
select seed.id, seed.name, c.id, seed.price, seed.badge, seed.badge_class, seed.image_url, seed.description, seed.light, seed.sort_order
from (
	values
	(1, 'Гортензія волотиста', 'Декоративні кущі', 450, 'Хіт продажу', 'bg-[#fff3ad] text-[#244f22]', 'https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=900&q=85', 'Пишне тривале цвітіння та добра зимостійкість.', 'Напівтінь', 10),
	(2, 'Ялівець Blue Arrow', 'Хвойні рослини', 380, 'Рекомендуємо', 'bg-[#dcebd7] text-[#244f22]', 'https://images.unsplash.com/photo-1604762512526-b7ce049b5764?auto=format&fit=crop&w=900&q=85', 'Струнка блакитна хвоя для акцентів і живих огорож.', 'Сонце', 20),
	(3, 'Троянда флорибунда', 'Садові рослини', 290, 'Популярне', 'bg-[#f7dfdf] text-[#713d3d]', 'https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&w=900&q=85', 'Рясне хвилеподібне цвітіння протягом усього літа.', 'Сонце', 30),
	(4, 'Лаванда вузьколиста', 'Сезонні рослини', 160, 'Вибір сезону', 'bg-[#e7dff4] text-[#55406f]', 'https://images.unsplash.com/photo-1499002238440-d264edd596ec?auto=format&fit=crop&w=900&q=85', 'Ароматна, невибаглива та приваблює запилювачів.', 'Сонце', 40),
	(5, 'Туя Smaragd', 'Хвойні рослини', 320, 'Хіт продажу', 'bg-[#fff3ad] text-[#244f22]', 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=900&q=85', 'Щільна крона, насичений колір і простий догляд.', 'Сонце', 50),
	(6, 'Самшит вічнозелений', 'Декоративні кущі', 240, 'Рекомендуємо', 'bg-[#dcebd7] text-[#244f22]', 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?auto=format&fit=crop&w=900&q=85', 'Добре тримає форму та підходить для бордюрів.', 'Напівтінь', 60),
	(7, 'Півонія молочноквіткова', 'Садові рослини', 350, 'Популярне', 'bg-[#f7dfdf] text-[#713d3d]', 'https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=900&q=85', 'Великі ароматні квіти й десятиліття на одному місці.', 'Сонце', 70),
	(8, 'Барбарис Тунберга', 'Декоративні кущі', 220, 'Вибір сезону', 'bg-[#e7dff4] text-[#55406f]', 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=900&q=85', 'Яскраве листя для кольорових акцентів у саду.', 'Сонце', 80),
	(9, 'Яблуня декоративна', 'Плодові рослини', 520, 'Хіт продажу', 'bg-[#fff3ad] text-[#244f22]', 'https://images.unsplash.com/photo-1523528283115-9bf9b1699245?auto=format&fit=crop&w=900&q=85', 'Весняне цвітіння та декоративні плоди восени.', 'Сонце', 90),
	(10, 'Хоста Blue Angel', 'Багаторічні рослини', 180, 'Рекомендуємо', 'bg-[#dcebd7] text-[#244f22]', 'https://images.unsplash.com/photo-1520412099551-62b6bafeb5bb?auto=format&fit=crop&w=900&q=85', 'Велике сизе листя для затінених куточків.', 'Тінь', 100),
	(11, 'Спірея японська', 'Декоративні кущі', 210, 'Популярне', 'bg-[#f7dfdf] text-[#713d3d]', 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=900&q=85', 'Компактний кущ із ніжним літнім цвітінням.', 'Сонце', 110),
	(12, 'Клематис Jackmanii', 'В’юнкі рослини', 270, 'Вибір сезону', 'bg-[#e7dff4] text-[#55406f]', 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=900&q=85', 'Рясно квітуча ліана для пергол, арок і парканів.', 'Напівтінь', 120)
) as seed(id, name, category_name, price, badge, badge_class, image_url, description, light, sort_order)
join public.categories c on c.name = seed.category_name
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.categories', 'id'), coalesce((select max(id) from public.categories), 1), true);
select setval(pg_get_serial_sequence('public.products', 'id'), coalesce((select max(id) from public.products), 1), true);
